#include "app_bridge/src/lib.rs.h" // Generated by cxx
#include "novabridgestub.h"

NovaBridgeStub::NovaBridgeStub(QObject *parent) : QObject(parent) {
  // Call the Rust initialization function
  init_engine();
}

QString NovaBridgeStub::engineApiVersion() const { return "0.1.0"; }

void NovaBridgeStub::dispatchCommand(const QString &commandJson) {
  // Convert QString to rust::String and call execute_command
  rust::String result = execute_command(commandJson.toUtf8().constData());

  QString responseStr = QString::fromUtf8(result.c_str());
  qDebug("[NovaBridgeStub] Response from Rust: %s",
         qUtf8Printable(responseStr));

  // Отправляем событие в QML
  emit engineEventReceived(responseStr);
}
